name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      FASTK_DEST_DIR: /tmp/bin
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y libbz2-dev libcurl4-gnutls-dev liblzma-dev
      - run: gcc --version
      - run: make
      - run: mkdir -p "${FASTK_DEST_DIR}"
      - run: make install DEST_DIR="${FASTK_DEST_DIR}"
